<div class="locations flex flex-column flex-md-row all">
    <div class="location">
        <div class="name">Jylland</div>
        <div>Islandsvej 28</div>
        <div>8700 Horsens</div>
        <div>tlf. 76 28 38 00</div>
    </div>
    <div class="location">
        <div class="name">Fyn</div>
        <div>Cikorievej 24</div>
        <div>5220 Odense SØ</div>
        <div>tlf. 76 28 38 00</div>
    </div>
    <div class="location">
        <div class="name">Sjælland</div>
        <div>Herlev Hovedgade 201A</div>
        <div>2730 Herlev</div>
        <div>tlf. 76 28 38 00</div>
    </div>
</div>