<div class="locations flex all wrap">
    <div class="location">
        <div class="name">Herlev</div>
        <div>Herlev Hovedgade 201A</div>
        <div>2730 Herlev</div>
        <div>tlf. 39 55 98 00</div>
    </div>
    <div class="location">
        <div class="name">Horsens</div>
        <div>Islandsvej 28</div>
        <div>8700 Horsens</div>
        <div>tlf. 76 28 38 00</div>
    </div>
    <div class="location">
        <div class="name">Odense</div>
        <div>Cikorievej 24</div>
        <div>5220 Odense SO</div>
        <div>tlf. 76 28 38 00</div>
    </div>
</div>