<span class="item"><a href="arbejdstoj">Test Link 1</a></span>
<span class="item"><a href="medie">Test Link 2</a></span>
<span class="item">
    <span class="dropdown">
        <i class="fas fa-bars" data-toggle="dropdown"></i>
        <div class="dropdown-menu" >
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
        </div>
    </span>
</span>